services:
  - type: web
    name: portfolio-website
    runtime: node
    buildCommand: npm install --legacy-peer-deps && npm install typescript @types/react @types/node @types/react-dom --save-dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
